site_name: SPbUnited
site_url: https://spbunited.ru/
site_description: SPbUnited team knowledge base.
site_author: Glazov Yuri

# repo_url: https://github.com/SPBUnited/team-website

theme:
  name: null
  custom_dir: "spbunited-theme/"
  navigation_depth: 2
  color_mode: dark
  user_color_mode_toggle: false
  highlightjs: false
  language: ru
  analytics: { gtag: "G-LR3D14PQPR" }

nav:
  - Основное: "index.md"
  - Введение в SSL:
      - Общая информация: "entry-guide/guide.md"
      - Пример программы: "entry-guide/communication.md"
  - Устройство робота:
      - Конструкция: "hardware/construction.md"
      - Электроника: "hardware/electronics.md"
  - Программное обеспечение:
      - Используемые программы: "software/programs.md"
      # - Стратегия игры: "software/strategy.md"
      - Алгоритмы: "software/algorithms.md"
  - Ссылки: "links.md"

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
extra_css:
  - ./css/monokai.css
  
markdown_extensions:
  - mdx_math
  - codehilite:
      guess_lang: true
      use_pygments: true
      linenums: true
