site_name: SPbUnited
site_url: https://spbunited.ru/
site_description: SPbUnited team knowledge base.
site_author: Glazov Yuri

# repo_url: https://github.com/SPBUnited/team-website

theme:
  name: null
  custom_dir: "spbunited-theme/"
  navigation_depth: 2
  color_mode: dark
  # user_color_mode_toggle: true
  language: ru
  analytics: { gtag: "G-LR3D14PQPR" }
  highlightjs: true
  hljs_languages:
    - yaml
    - django

nav:
  - Основное: "index.md"
  - Введение в Small Size League: "entry-guide/guide.md"
  - Устройство робота:
      - Конструкция: "hardware/construction.md"
      - Электроника: "hardware/electronics.md"
  - Программное обеспечение:
      - Используемые программы: "software/programs.md"
      # - Стратегия игры: "software/strategy.md"
      - Алгоритмы: "software/algorithms.md"
  - Ссылки: "links.md"

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math
